debug #2

diff --git a/.github/workflows/run-scraper.yml b/.github/workflows/run-scraper.yml
--- a/.github/workflows/run-scraper.yml
+++ b/.github/workflows/run-scraper.yml
@@ -16,42 +16,52 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    # Optional: print files
-    - name: List all files
-      run: ls -R
-    
-    - name: Print working directory
-      run: pwd
-
-    - name: Check SQLite Version
-      run: sqlite3 --version
-
-    - name: Verify database file
-      run: |
-        if [ -f "assets/immo_elliza.db" ]; then
-          echo "Database file exists";
-        else
-          echo "Database file is missing";
-          exit 1;
-        fi
-    
     # Step 1: Checkout the repository
     - name: Checkout code
       uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
 
-    # Step 2: Set up Python environment
+    # Step 2: Verify assets directory and database file
+    - name: Verify assets directory
+      run: |
+        if [ -d "assets" ]; then
+          echo "Assets directory exists";
+          if [ -f "assets/immo_elliza.db" ]; then
+            echo "Database file exists in assets";
+          else
+            echo "Database file is missing in assets";
+            exit 1;
+          fi
+        else
+          echo "Assets directory is missing";
+          exit 1;
+        fi
+
+    # Step 3: Set up Python environment
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: "3.11.9" # Replace with the Python version your script requires
 
-    # Step 3: Install dependencies
+    # Step 4: Install dependencies
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
 
-    # Step 4: Run the script
+    # Step 5: Print working directory and list all files
+    - name: Print working directory
+      run: pwd
+
+    - name: List all files
+      run: ls -R
+
+    # Step 6: Check SQLite version
+    - name: Check SQLite Version
+      run: sqlite3 --version
+
+    # Step 7: Run the scraper
     - name: Run scraper
       run: |
         python scraper.py
